### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by djplus81** [thiago-dev/fivem-hypnonema#71] opened 2021-11-06 01:52 UTC
![Screenshot 2021-11-05 215016](https://user-images.githubusercontent.com/90886403/140593904-bc5edb1b-ef1e-4597-8edc-42c8c23027cc.png)

**Comment by thiago-dev** [comment] 2021-11-06 14:10
duplicate of #43

**Closed by thiago-dev** 2021-11-06 14:10 UTC
Labels: bug, duplicate

**Comment by djplus81** [comment] 2021-11-07 00:12
duplicate of #43

**Comment by djplus81** [comment] 2021-11-07 00:13
So which command should I duplicate or just should I put #43 twice?
